version: 2
updates:
    -   package-ecosystem: "github-actions"
        directory: "/"
        schedule:
            interval: "hourly"
    -   package-ecosystem: "maven"
        directory: "/"
        schedule:
            interval: "hourly"
    -   package-ecosystem: "docker"
        directory: "/"
        schedule:
            interval: "hourly"
